import 'dart:io';
import 'dart:isolate';
import 'dart:convert';
import 'dart:typed_data';
import 'package:crypto/crypto.dart';
import 'package:dio/dio.dart';
import 'package:image/image.dart' as img;
import 'package:path/path.dart' as path;
import '../../core/network/bangumi_user_agent.dart';
import 'tier_print_models.dart';
import 'tier_print_cancel.dart';

class TierPrintCovers {
  TierPrintCovers({required this.cache, Dio? dio})
    : _dio =
          dio ??
          Dio(
            BaseOptions(
              connectTimeout: const Duration(seconds: 12),
              receiveTimeout: const Duration(seconds: 20),
              followRedirects: false,
              headers: {'User-Agent': muBangumiUserAgent},
            ),
          );
  final Directory cache;
  final Dio _dio;
  static const maxSourceBytes = 5 * 1024 * 1024;
  void close() => _dio.close(force: true);

  Future<Uint8List> _one(TierPrintEntry entry, CancelToken cancel) async {
    cancel.throwIfCancellationRequested();
    final uri = Uri.tryParse(entry.coverUrl);
    if (uri == null ||
        uri.scheme != 'https' ||
        uri.host != 'lain.bgm.tv' ||
        uri.userInfo.isNotEmpty ||
        uri.port != 443) {
      throw const FormatException('没有可用的官方封面');
    }
    final key = sha256.convert(utf8.encode('v1:${entry.coverUrl}')).toString();
    final file = File(path.join(cache.path, '$key.jpg'));
    if (await file.exists()) {
      final size = await file.length();
      if (size > 0 && size < 1024 * 1024) {
        final bytes = await file.readAsBytes();
        // Reject truncated cache entries instead of embedding broken data.
        if (bytes.length > 4 &&
            bytes[0] == 0xff &&
            bytes[1] == 0xd8 &&
            bytes[bytes.length - 2] == 0xff &&
            bytes.last == 0xd9) {
          return bytes;
        }
      }
    }
    final response = await _dio.get<ResponseBody>(
      uri.toString(),
      cancelToken: cancel,
      options: Options(responseType: ResponseType.stream),
    );
    final body = response.data;
    if (body == null) throw const FormatException('封面为空');
    final chunks = BytesBuilder(copy: false);
    await for (final chunk in body.stream) {
      cancel.throwIfCancellationRequested();
      if (chunks.length + chunk.length > maxSourceBytes) {
        throw const FormatException('封面文件过大');
      }
      chunks.add(chunk);
    }
    final source = chunks.takeBytes();
    final bytes = await Isolate.run(() => normalizeTierCover(source));
    cancel.throwIfCancellationRequested();
    await cache.create(recursive: true);
    // Cache failures cannot invalidate a successfully downloaded cover.
    try {
      await file.writeAsBytes(bytes, flush: true);
    } catch (_) {}
    return bytes;
  }

  Future<Map<int, Uint8List>> load(
    List<TierPrintEntry> entries, {
    required CancelToken cancel,
    Map<int, Uint8List> existing = const {},
    void Function(int done, int failed)? progress,
  }) async {
    final result = <int, Uint8List>{};
    var next = 0, done = 0, failed = 0;
    Future<void> worker() async {
      while (next < entries.length) {
        cancel.throwIfCancellationRequested();
        final entry = entries[next++];
        try {
          result[entry.id] = existing[entry.id] ?? await _one(entry, cancel);
        } catch (_) {
          cancel.throwIfCancellationRequested();
          failed++;
        }
        progress?.call(++done, failed);
      }
    }

    await Future.wait([worker(), worker()]);
    await _prune();
    return result;
  }

  Future<void> _prune() async {
    // Only evict files generated by this feature inside its own cache folder.
    try {
      if (!await cache.exists()) return;
      final root = path.normalize(path.absolute(cache.path));
      final files = <({File file, DateTime modified, int size})>[];
      await for (final entity in cache.list(followLinks: false)) {
        if (entity is! File ||
            !RegExp(
              r'^[a-f0-9]{64}\.jpg$',
            ).hasMatch(path.basename(entity.path)) ||
            !path.isWithin(root, path.normalize(path.absolute(entity.path)))) {
          continue;
        }
        final stat = await entity.stat();
        files.add((file: entity, modified: stat.modified, size: stat.size));
      }
      files.sort((a, b) => b.modified.compareTo(a.modified));
      var bytes = 0;
      for (var i = 0; i < files.length; i++) {
        bytes += files[i].size;
        if (i >= 4000 || bytes > 240 * 1024 * 1024) {
          await files[i].file.delete();
        }
      }
    } catch (_) {}
  }
}

Uint8List normalizeTierCover(Uint8List source) {
  final decoder = img.findDecoderForData(source);
  final info = decoder?.startDecode(source);
  if (info == null ||
      info.width <= 0 ||
      info.height <= 0 ||
      info.width * info.height > 8000000) {
    throw const FormatException('封面格式或尺寸无效');
  }
  final decoded = decoder!.decodeFrame(0);
  if (decoded == null) throw const FormatException('封面无法解码');
  final image = img.bakeOrientation(decoded);
  final resized = image.width > 560 || image.height > 560
      ? img.copyResize(
          image,
          width: image.width >= image.height ? 560 : null,
          height: image.height > image.width ? 560 : null,
          interpolation: img.Interpolation.average,
        )
      : image;
  resized.exif = img.ExifData();
  return img.encodeJpg(resized, quality: 90);
}
